# Generated by Django 5.1.4 on 2024-12-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_bot_functionality', '0002_alter_notification_sent_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-send_at']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sent_at',
            new_name='send_at',
        ),
    ]
