# Generated by Django 5.1.4 on 2024-12-18 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_bot_functionality', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main_bot_functionality.specialist'),
        ),
    ]
