# Generated by Django 5.1.4 on 2024-12-19 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_bot_functionality', '0005_remove_specialist_location_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Продолжительность услуги в минутах')),
                ('category', models.CharField(choices=[('Стрижка волос', 'Стрижка волос'), ('Борода', 'Борода'), ('Укладка волос', 'Укладка волос'), ('Окрашивание волос', 'Окрашивание волос'), ('Уход за лицом', 'Уход за лицом')], max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main_bot_functionality.service'),
        ),
    ]
