# Generated by Django 5.1.4 on 2024-12-19 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_bot_functionality', '0008_workinghour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='specialist',
        ),
        migrations.RemoveField(
            model_name='salonmanager',
            name='number',
        ),
        migrations.AddField(
            model_name='appointment',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main_bot_functionality.salon'),
        ),
        migrations.AddField(
            model_name='salon',
            name='specialists',
            field=models.ManyToManyField(related_name='salons', to='main_bot_functionality.specialist'),
        ),
        migrations.AddField(
            model_name='salonmanager',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Отправлено', 'Отправлено'), ('Не отправлено', 'Не отправлено')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Оплачено', 'Оплачено'), ('Не оплачено', 'Не оплачено')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='specialization',
        ),
        migrations.AddField(
            model_name='specialist',
            name='specialization',
            field=models.ManyToManyField(related_name='specialists', to='main_bot_functionality.service'),
        ),
    ]
