# Generated by Django 5.1.4 on 2024-12-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_bot_functionality', '0009_remove_salon_specialist_remove_salonmanager_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Стрижка волос', 'Стрижка волос'), ('Борода', 'Борода'), ('Укладка волос', 'Укладка волос'), ('Окрашивание волос', 'Окрашивание волос'), ('Уход за лицом', 'Уход за лицом')], max_length=200, null=True),
        ),
    ]
