# Generated by Django 5.1.4 on 2024-12-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_bot_functionality', '0010_alter_service_options_remove_service_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='workinghour',
            name='salon',
        ),
        migrations.AddField(
            model_name='workinghour',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='main_bot_functionality.specialist'),
        ),
    ]
