# Generated by Django 5.1.4 on 2024-12-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_bot_functionality', '0013_remove_specialist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
    ]
