# Generated by Django 5.1.4 on 2024-12-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_bot_functionality', '0015_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
    ]
