# Generated by Django 5.1.4 on 2024-12-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_bot_functionality', '0016_remove_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
