# Generated by Django 5.1.4 on 2024-12-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_bot_functionality', '0017_specialist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='tg_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
